// This file is generated by omniidl (C++ backend) - omniORB_4_1. Do not edit.

#include "NET_SerialTracking.h"

OMNI_USING_NAMESPACE(omni)

static const char* _0RL_dyn_library_version = omniORB_4_1_dyn;

static ::CORBA::TypeCode::_Tracker _0RL_tcTrack(__FILE__);

#if defined(HAS_Cplusplus_Namespace) && defined(_MSC_VER)
// MSVC++ does not give the constant external linkage otherwise.
namespace VSerialTracking { 
  const ::CORBA::TypeCode_ptr _tc_SimpleCommand = CORBA::TypeCode::PR_interface_tc("IDL:VSerialTracking/SimpleCommand:1.0", "SimpleCommand", &_0RL_tcTrack);
} 
#else
const ::CORBA::TypeCode_ptr VSerialTracking::_tc_SimpleCommand = CORBA::TypeCode::PR_interface_tc("IDL:VSerialTracking/SimpleCommand:1.0", "SimpleCommand", &_0RL_tcTrack);
#endif

static void _0RL_VSerialTracking_mSimpleCommand_marshal_fn(cdrStream& _s, void* _v)
{
  omniObjRef* _o = (omniObjRef*)_v;
  omniObjRef::_marshal(_o, _s);
}
static void _0RL_VSerialTracking_mSimpleCommand_unmarshal_fn(cdrStream& _s, void*& _v)
{
  omniObjRef* _o = omniObjRef::_unMarshal(VSerialTracking::SimpleCommand::_PD_repoId, _s);
  _v = _o;
}
static void _0RL_VSerialTracking_mSimpleCommand_destructor_fn(void* _v)
{
  omniObjRef* _o = (omniObjRef*)_v;
  if (_o)
    omni::releaseObjRef(_o);
}

void operator<<=(::CORBA::Any& _a, VSerialTracking::SimpleCommand_ptr _o)
{
  VSerialTracking::SimpleCommand_ptr _no = VSerialTracking::SimpleCommand::_duplicate(_o);
  _a.PR_insert(VSerialTracking::_tc_SimpleCommand,
               _0RL_VSerialTracking_mSimpleCommand_marshal_fn,
               _0RL_VSerialTracking_mSimpleCommand_destructor_fn,
               _no->_PR_getobj());
}
void operator<<=(::CORBA::Any& _a, VSerialTracking::SimpleCommand_ptr* _op)
{
  _a.PR_insert(VSerialTracking::_tc_SimpleCommand,
               _0RL_VSerialTracking_mSimpleCommand_marshal_fn,
               _0RL_VSerialTracking_mSimpleCommand_destructor_fn,
               (*_op)->_PR_getobj());
  *_op = VSerialTracking::SimpleCommand::_nil();
}

::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, VSerialTracking::SimpleCommand_ptr& _o)
{
  void* _v;
  if (_a.PR_extract(VSerialTracking::_tc_SimpleCommand,
                    _0RL_VSerialTracking_mSimpleCommand_unmarshal_fn,
                    _0RL_VSerialTracking_mSimpleCommand_marshal_fn,
                    _0RL_VSerialTracking_mSimpleCommand_destructor_fn,
                    _v)) {
    omniObjRef* _r = (omniObjRef*)_v;
    if (_r)
      _o = (VSerialTracking::SimpleCommand_ptr)_r->_ptrToObjRef(VSerialTracking::SimpleCommand::_PD_repoId);
    else
      _o = VSerialTracking::SimpleCommand::_nil();
    return 1;
  }
  return 0;
}

