// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.
#ifndef __NET__Message_hh__
#define __NET__Message_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_NET__Message
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_NET__Message
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_NET__Message
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





_CORBA_MODULE VMessaging

_CORBA_MODULE_BEG

  enum NET_DistributionRealm { NET_DR_LOCAL, NET_DR_GLOBAL /*, __max_NET_DistributionRealm=0xffffffff */ };
  typedef NET_DistributionRealm& NET_DistributionRealm_out;

  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_NET_DistributionRealm;

  enum NET_PayloadSignificance { NET_PS_ROUTINE, NET_PS_UNUSUAL, NET_PS_EXCEPTIONAL, NET_PS_CRITICAL /*, __max_NET_PayloadSignificance=0xffffffff */ };
  typedef NET_PayloadSignificance& NET_PayloadSignificance_out;

  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_NET_PayloadSignificance;

  struct NET_Message {
    typedef _CORBA_ConstrType_Variable_Var<NET_Message> _var_type;

    
    ::CORBA::Long zone;

    ::CORBA::String_member hostname;

    ::CORBA::String_member program;

    ::CORBA::String_member title;

    NET_DistributionRealm realm;

    NET_PayloadSignificance significance;

    ::CORBA::String_member message;

    ::CORBA::String_member details;

    ::CORBA::String_member function;

    ::CORBA::Long tv_sec;

    ::CORBA::Long tv_usec;

  

    void operator>>= (cdrStream &) const;
    void operator<<= (cdrStream &);
  };

  typedef NET_Message::_var_type NET_Message_var;

  typedef _CORBA_ConstrType_Variable_OUT_arg< NET_Message,NET_Message_var > NET_Message_out;

  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_NET_Message;

_CORBA_MODULE_END



_CORBA_MODULE POA_VMessaging
_CORBA_MODULE_BEG

_CORBA_MODULE_END



_CORBA_MODULE OBV_VMessaging
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr

inline void operator >>=(VMessaging::NET_DistributionRealm _e, cdrStream& s) {
  ::operator>>=((::CORBA::ULong)_e, s);
}

inline void operator <<= (VMessaging::NET_DistributionRealm& _e, cdrStream& s) {
  ::CORBA::ULong _0RL_e;
  ::operator<<=(_0RL_e,s);
  if (_0RL_e <= VMessaging::NET_DR_GLOBAL) {
    _e = (VMessaging::NET_DistributionRealm) _0RL_e;
  }
  else {
    OMNIORB_THROW(MARSHAL,_OMNI_NS(MARSHAL_InvalidEnumValue),
                  (::CORBA::CompletionStatus)s.completion());
  }
}

void operator<<=(::CORBA::Any& _a, VMessaging::NET_DistributionRealm _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, VMessaging::NET_DistributionRealm& _s);

inline void operator >>=(VMessaging::NET_PayloadSignificance _e, cdrStream& s) {
  ::operator>>=((::CORBA::ULong)_e, s);
}

inline void operator <<= (VMessaging::NET_PayloadSignificance& _e, cdrStream& s) {
  ::CORBA::ULong _0RL_e;
  ::operator<<=(_0RL_e,s);
  if (_0RL_e <= VMessaging::NET_PS_CRITICAL) {
    _e = (VMessaging::NET_PayloadSignificance) _0RL_e;
  }
  else {
    OMNIORB_THROW(MARSHAL,_OMNI_NS(MARSHAL_InvalidEnumValue),
                  (::CORBA::CompletionStatus)s.completion());
  }
}

void operator<<=(::CORBA::Any& _a, VMessaging::NET_PayloadSignificance _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, VMessaging::NET_PayloadSignificance& _s);

extern void operator<<=(::CORBA::Any& _a, const VMessaging::NET_Message& _s);
extern void operator<<=(::CORBA::Any& _a, VMessaging::NET_Message* _sp);
extern _CORBA_Boolean operator>>=(const ::CORBA::Any& _a, VMessaging::NET_Message*& _sp);
extern _CORBA_Boolean operator>>=(const ::CORBA::Any& _a, const VMessaging::NET_Message*& _sp);





#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_NET__Message
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_NET__Message
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_NET__Message
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_NET__Message
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_NET__Message
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_NET__Message
#endif

#endif  // __NET__Message_hh__

